name: SimpleVaultReset
version: '1.1'
main: cn.simplevaultreset.SimpleVaultReset
api-version: '1.21'
folia-supported: true

commands:
  simplevaultreset:
    description: Main command.
    usage: /<command>
    aliases: [svr]

permissions:
  simplevaultreset.reload:
    default: op
  simplevaultreset.giveominous:
    default: op
  simplevaultreset.resetchunk:
    default: op